import type { Metadata } from "next";
import { Inter, Roboto_Condensed, Sora } from "next/font/google";
import "@/app/globals.css";
import PrelineScript from "@/components/library/PrelineScript";
import Navbar from "@/components/Layout/Navbar";
import { Providers } from "./provide";

const inter = Inter({ subsets: ["latin"] });
const soraSans = Sora({
  variable: "--soraSans-font",
  subsets: ["latin"],
  display: "fallback",
  weight: ["300", "400", "500", "600", "700", "800"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--robotoCondensed-font",
  subsets: ["latin"],
  display: "fallback",
  weight: ["400", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} container`}
        suppressHydrationWarning={true}
      >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
      <PrelineScript />
    </html>
  );
}
